=== SQL-Storm/OLAPBench/schemas/dbschema.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Schema for Database Schema Definitions",
  "definitions": {
    "column": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "type": { "type": "string" },
        "_eval": { "type": "string" }
      },
      "additionalProperties": false,
      "required": [ "name", "type" ]
    },
    "primary key": {
      "type": "object",
      "properties": {
        "column": { "type": "string" },
        "columns": { "type": "array", "items": { "type": "string" } }
      },
      "additionalProperties": false,
      "oneOf": [
        { "required": [ "column" ] },
        { "required": [ "columns" ] }
      ]
    },
    "foreign key": {
      "type": "object",
      "properties": {
        "column": { "type": "string" },
        "columns": { "type": "array", "items": { "type": "string" } },
        "foreign table": { "type": "string" },
        "foreign column": { "type": "string" },
        "foreign columns": { "type": "array", "items": { "type": "string" } }
      },
      "additionalProperties": false,
      "oneOf": [
        { "required": [ "column", "foreign table", "foreign column" ] },
        { "required": [ "columns", "foreign table", "foreign columns" ] }
      ]
    },
    "table": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "columns": { "type": "array", "items": { "$ref": "#/definitions/column" } },
        "primary key": { "$ref": "#/definitions/primary key" },
        "foreign keys": { "type": "array", "items": { "$ref": "#/definitions/foreign key" } },
        "_eval": { "type": "string" },
        "initially empty": { "type": "boolean", "default": false }
      },
      "additionalProperties": false,
      "required": [ "name", "columns" ]
    },
    "query": {
      "type": "object",
      "properties": {
        "query": { "type": "string" },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "additionalProperties": false,
      "required": [ "query" ]
    }
  },
  "type": "object",
  "properties": {
    "file_ending": { "type": "string", "default": "tbl" },
    "delimiter": {
      "type": "string",
      "default": ","
    },
    "format": {
      "type": "string",
      "enum": [ "text", "csv" ],
      "default": "text"
    },
    "csv_escape": {
      "type": "string",
      "default": "\\"
    },
    "null": {
      "type": "string",
      "default": ""
    },
    "tables": {
      "type": "array",
      "items": { "$ref": "#/definitions/table" }
    },
    "header": { "type": "boolean", "default": false },
    "lowercase_names": { "type": "boolean", "default": false },
    "escape_names": { "type": "boolean", "default": true },
    "additional_sql_create": { "type": "array", "items": { "$ref": "#/definitions/query" } },
    "additional_sql_insert": { "type": "array", "items": { "$ref": "#/definitions/query" } }
  },
  "additionalProperties": false,
  "required": [ "file_ending", "delimiter", "format", "tables" ]
}

=== SQL-Storm/OLAPBench/benchmarks/tpch/tpch.dbschema.json
{
  "file_ending": "tbl",
  "delimiter": "|",
  "format": "text",
  "null": "",
  "tables": [
    {
      "name": "part",
      "columns": [
        { "name": "p_partkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "p_partkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "p_name", "type": "varchar(55) not null" },
        { "name": "p_mfgr", "type": "char(25) not null" },
        { "name": "p_brand", "type": "char(10) not null" },
        { "name": "p_type", "type": "varchar(25) not null" },
        { "name": "p_size", "type": "integer not null" },
        { "name": "p_container", "type": "char(10) not null" },
        { "name": "p_retailprice", "type": "decimal(12,2) not null" },
        { "name": "p_comment", "type": "varchar(23) not null" }
      ],
      "primary key": { "column": "p_partkey" }
    },
    {
      "name": "region",
      "columns": [
        { "name": "r_regionkey", "type": "integer not null" },
        { "name": "r_name", "type": "char(25) not null" },
        { "name": "r_comment", "type": "varchar(152) not null" }
      ],
      "primary key": { "column": "r_regionkey" }
    },
    {
      "name": "nation",
      "columns": [
        { "name": "n_nationkey", "type": "integer not null" },
        { "name": "n_name", "type": "char(25) not null" },
        { "name": "n_regionkey", "type": "integer not null" },
        { "name": "n_comment", "type": "varchar(152) not null" }
      ],
      "primary key": { "column": "n_nationkey" },
      "foreign keys": [ { "column": "n_regionkey", "foreign table": "region", "foreign column": "r_regionkey" } ]
    },
    {
      "name": "supplier",
      "columns": [
        { "name": "s_suppkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "s_suppkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "s_name", "type": "char(25) not null" },
        { "name": "s_address", "type": "varchar(40) not null" },
        { "name": "s_nationkey", "type": "integer not null" },
        { "name": "s_phone", "type": "char(15) not null" },
        { "name": "s_acctbal", "type": "decimal(12,2) not null" },
        { "name": "s_comment", "type": "varchar(101) not null" }
      ],
      "primary key": { "column": "s_suppkey" },
      "foreign keys": [ { "column": "s_nationkey", "foreign table": "nation", "foreign column": "n_nationkey" } ]
    },
    {
      "name": "partsupp",
      "columns": [
        { "name": "ps_partkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "ps_partkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "ps_suppkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "ps_suppkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "ps_availqty", "type": "integer not null" },
        { "name": "ps_supplycost", "type": "decimal(12,2) not null" },
        { "name": "ps_comment", "type": "varchar(199) not null" }
      ],
      "primary key": { "columns": [ "ps_partkey", "ps_suppkey" ] },
      "foreign keys": [
        { "column": "ps_partkey", "foreign table": "part", "foreign column": "p_partkey" },
        { "column": "ps_suppkey", "foreign table": "supplier", "foreign column": "s_suppkey" }
      ]
    },
    {
      "name": "customer",
      "columns": [
        { "name": "c_custkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "c_custkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "c_name", "type": "varchar(25) not null" },
        { "name": "c_address", "type": "varchar(40) not null" },
        { "name": "c_nationkey", "type": "integer not null" },
        { "name": "c_phone", "type": "char(15) not null" },
        { "name": "c_acctbal", "type": "decimal(12,2) not null" },
        { "name": "c_mktsegment", "type": "char(10) not null" },
        { "name": "c_comment", "type": "varchar(117) not null" }
      ],
      "primary key": { "column": "c_custkey" },
      "foreign keys": [ { "column": "c_nationkey", "foreign table": "nation", "foreign column": "n_nationkey" } ]
    },
    {
      "name": "orders",
      "columns": [
        { "name": "o_orderkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "o_orderkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "o_custkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "o_custkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "o_orderstatus", "type": "char(1) not null" },
        { "name": "o_totalprice", "type": "decimal(12,2) not null" },
        { "name": "o_orderdate", "type": "date not null" },
        { "name": "o_orderpriority", "type": "char(15) not null" },
        { "name": "o_clerk", "type": "char(15) not null" },
        { "name": "o_shippriority", "type": "integer not null" },
        { "name": "o_comment", "type": "varchar(79) not null" }
      ],
      "primary key": { "column": "o_orderkey" },
      "foreign keys": [ { "column": "o_custkey", "foreign table": "customer", "foreign column": "c_custkey" } ]
    },
    {
      "name": "lineitem",
      "columns": [
        { "name": "l_orderkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "l_orderkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "l_partkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "l_partkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "l_suppkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "l_suppkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "l_linenumber", "type": "integer not null" },
        { "name": "l_quantity", "type": "decimal(12,2) not null" },
        { "name": "l_extendedprice", "type": "decimal(12,2) not null" },
        { "name": "l_discount", "type": "decimal(12,2) not null" },
        { "name": "l_tax", "type": "decimal(12,2) not null" },
        { "name": "l_returnflag", "type": "char(1) not null" },
        { "name": "l_linestatus", "type": "char(1) not null" },
        { "name": "l_shipdate", "type": "date not null" },
        { "name": "l_commitdate", "type": "date not null" },
        { "name": "l_receiptdate", "type": "date not null" },
        { "name": "l_shipinstruct", "type": "char(25) not null" },
        { "name": "l_shipmode", "type": "char(10) not null" },
        { "name": "l_comment", "type": "varchar(44) not null" }
      ],
      "primary key": { "columns": [ "l_orderkey", "l_linenumber" ] },
      "foreign keys": [
        { "column": "l_orderkey", "foreign table": "orders", "foreign column": "o_orderkey" },
        { "column": "l_partkey", "foreign table": "part", "foreign column": "p_partkey" },
        { "column": "l_suppkey", "foreign table": "supplier", "foreign column": "s_suppkey" },
        {
          "columns": [ "l_partkey", "l_suppkey" ],
          "foreign table": "partsupp",
          "foreign columns": [ "ps_partkey", "ps_suppkey" ]
        }
      ]
    }
  ]
}
