=== SQL-Storm/OLAPBench/schemas/dbschema.schema.json
{
  "$schema": "https://json-schema.org/draft-07/schema",
  "title": "Schema for Database Schema Definitions",
  "definitions": {
    "column": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "type": { "type": "string" },
        "_eval": { "type": "string" }
      },
      "additionalProperties": false,
      "required": [ "name", "type" ]
    },
    "primary key": {
      "type": "object",
      "properties": {
        "column": { "type": "string" },
        "columns": { "type": "array", "items": { "type": "string" } }
      },
      "additionalProperties": false,
      "oneOf": [
        { "required": [ "column" ] },
        { "required": [ "columns" ] }
      ]
    },
    "foreign key": {
      "type": "object",
      "properties": {
        "column": { "type": "string" },
        "columns": { "type": "array", "items": { "type": "string" } },
        "foreign table": { "type": "string" },
        "foreign column": { "type": "string" },
        "foreign columns": { "type": "array", "items": { "type": "string" } }
      },
      "additionalProperties": false,
      "oneOf": [
        { "required": [ "column", "foreign table", "foreign column" ] },
        { "required": [ "columns", "foreign table", "foreign columns" ] }
      ]
    },
    "table": {
      "type": "object",
      "properties": {
        "name": { "type": "string" },
        "columns": { "type": "array", "items": { "$ref": "#/definitions/column" } },
        "primary key": { "$ref": "#/definitions/primary key" },
        "foreign keys": { "type": "array", "items": { "$ref": "#/definitions/foreign key" } },
        "_eval": { "type": "string" },
        "initially empty": { "type": "boolean", "default": false }
      },
      "additionalProperties": false,
      "required": [ "name", "columns" ]
    },
    "query": {
      "type": "object",
      "properties": {
        "query": { "type": "string" },
        "tags": {
          "type": "array",
          "items": { "type": "string" }
        }
      },
      "additionalProperties": false,
      "required": [ "query" ]
    }
  },
  "type": "object",
  "properties": {
    "file_ending": { "type": "string", "default": "tbl" },
    "delimiter": {
      "type": "string",
      "default": ","
    },
    "format": {
      "type": "string",
      "enum": [ "text", "csv" ],
      "default": "text"
    },
    "csv_escape": {
      "type": "string",
      "default": "\\"
    },
    "null": {
      "type": "string",
      "default": ""
    },
    "tables": {
      "type": "array",
      "items": { "$ref": "#/definitions/table" }
    },
    "header": { "type": "boolean", "default": false },
    "lowercase_names": { "type": "boolean", "default": false },
    "escape_names": { "type": "boolean", "default": true },
    "additional_sql_create": { "type": "array", "items": { "$ref": "#/definitions/query" } },
    "additional_sql_insert": { "type": "array", "items": { "$ref": "#/definitions/query" } }
  },
  "additionalProperties": false,
  "required": [ "file_ending", "delimiter", "format", "tables" ]
}

=== SQL-Storm/OLAPBench/benchmarks/ssb/ssb.dbschema.json
{
  "file_ending": "tbl",
  "delimiter": "|",
  "format": "text",
  "csv_escape": "\\",
  "null": "",
  "tables": [
    {
      "name": "date",
      "columns": [
        { "name": "d_datekey", "type": "integer" },
        { "name": "d_date", "type": "char(18)" },
        { "name": "d_dayofweek", "type": "char(9)" },
        { "name": "d_month", "type": "char(9)" },
        { "name": "d_year", "type": "integer" },
        { "name": "d_yearmonthnum", "type": "integer" },
        { "name": "d_yearmonth", "type": "char(7)" },
        { "name": "d_daynuminweek", "type": "integer" },
        { "name": "d_daynuminmonth", "type": "integer" },
        { "name": "d_daynuminyear", "type": "integer" },
        { "name": "d_monthnuminyear", "type": "integer" },
        { "name": "d_weeknuminyear", "type": "integer" },
        { "name": "d_sellingseason", "type": "varchar(12)" },
        { "name": "d_lastdayinweekfl", "type": "integer" },
        { "name": "d_lastdayinmonthfl", "type": "integer" },
        { "name": "d_holidayfl", "type": "integer" },
        { "name": "d_weekdayfl", "type": "integer" }
      ],
      "primary key": { "column": "d_datekey" }
    },
    {
      "name": "supplier",
      "columns": [
        { "name": "s_suppkey", "type": "integer" },
        { "name": "s_name", "type": "char(25) " },
        { "name": "s_address", "type": "varchar(25)" },
        { "name": "s_city", "type": "char(10) " },
        { "name": "s_nation", "type": "char(15) " },
        { "name": "s_region", "type": "char(12) " },
        { "name": "s_phone", "type": "char(15) " }
      ],
      "primary key": { "column": "s_suppkey" }
    },
    {
      "name": "customer",
      "columns": [
        { "name": "c_custkey", "type": "integer" },
        { "name": "c_name", "type": "varchar(25)" },
        { "name": "c_address", "type": "varchar(25)" },
        { "name": "c_city", "type": "char(10) " },
        { "name": "c_nation", "type": "char(15) " },
        { "name": "c_region", "type": "char(12) " },
        { "name": "c_phone", "type": "char(15) " },
        { "name": "c_mktsegment", "type": "char(10) " }
      ],
      "primary key": { "column": "c_custkey" }
    },
    {
      "name": "part",
      "columns": [
        { "name": "p_partkey", "type": "integer" },
        { "name": "p_name", "type": "varchar(22)" },
        { "name": "p_mfgr", "type": "char(6)" },
        { "name": "p_category", "type": "char(7)" },
        { "name": "p_brand1", "type": "char(9)" },
        { "name": "p_color", "type": "varchar(11)" },
        { "name": "p_type", "type": "varchar(25)" },
        { "name": "p_size", "type": "integer" },
        { "name": "p_container", "type": "char(10)" }
      ],
      "primary key": { "column": "p_partkey" }
    },
    {
      "name": "lineorder",
      "columns": [
        { "name": "lo_orderkey", "type": "integer not null", "_eval": "dataset.scale < 1000" },
        { "name": "lo_orderkey", "type": "bigint not null", "_eval": "dataset.scale >= 1000" },
        { "name": "lo_linenumber", "type": "integer" },
        { "name": "lo_custkey", "type": "integer" },
        { "name": "lo_partkey", "type": "integer" },
        { "name": "lo_suppkey", "type": "integer" },
        { "name": "lo_orderdate", "type": "integer" },
        { "name": "lo_orderpriority", "type": "char(15)" },
        { "name": "lo_shippriority", "type": "char(1)" },
        { "name": "lo_quantity", "type": "integer" },
        { "name": "lo_extendedprice", "type": "numeric(18, 2)" },
        { "name": "lo_ordtotalprice", "type": "numeric(18, 2)" },
        { "name": "lo_discount", "type": "integer" },
        { "name": "lo_revenue", "type": "numeric(18, 2)" },
        { "name": "lo_supplycost", "type": "numeric(18, 2)" },
        { "name": "lo_tax", "type": "integer" },
        { "name": "lo_commitdate", "type": "integer" },
        { "name": "lo_shipmode", "type": "char(10)" }
      ],
      "primary key": { "columns": [ "lo_orderkey", "lo_linenumber" ] },
      "foreign keys": [
        { "column": "lo_custkey", "foreign table": "customer", "foreign column": "c_custkey" },
        { "column": "lo_partkey", "foreign table": "part", "foreign column": "p_partkey" },
        { "column": "lo_suppkey", "foreign table": "supplier", "foreign column": "s_suppkey" },
        { "column": "lo_orderdate", "foreign table": "date", "foreign column": "d_datekey" },
        { "column": "lo_commitdate", "foreign table": "date", "foreign column": "d_datekey" }
      ]
    }
  ]
}

=== SQL-Storm/OLAPBench/benchmarks/clickbench/clickbench.dbschema.json
{
  "file_ending": "tsv",
  "delimiter": "\t",
  "format": "text",
  "escape_names": false,
  "tables": [
    {
      "name": "hits",
      "columns": [
        { "name": "WatchID", "type": "BIGINT NOT NULL" },
        { "name": "JavaEnable", "type": "SMALLINT NOT NULL" },
        { "name": "Title", "type": "TEXT NOT NULL" },
        { "name": "GoodEvent", "type": "SMALLINT NOT NULL" },
        { "name": "EventTime", "type": "TIMESTAMP NOT NULL" },
        { "name": "EventDate", "type": "Date NOT NULL" },
        { "name": "CounterID", "type": "INTEGER NOT NULL" },
        { "name": "ClientIP", "type": "INTEGER NOT NULL" },
        { "name": "RegionID", "type": "INTEGER NOT NULL" },
        { "name": "UserID", "type": "BIGINT NOT NULL" },
        { "name": "CounterClass", "type": "SMALLINT NOT NULL" },
        { "name": "OS", "type": "SMALLINT NOT NULL" },
        { "name": "UserAgent", "type": "SMALLINT NOT NULL" },
        { "name": "URL", "type": "TEXT NOT NULL" },
        { "name": "Referer", "type": "TEXT NOT NULL" },
        { "name": "IsRefresh", "type": "SMALLINT NOT NULL" },
        { "name": "RefererCategoryID", "type": "SMALLINT NOT NULL" },
        { "name": "RefererRegionID", "type": "INTEGER NOT NULL" },
        { "name": "URLCategoryID", "type": "SMALLINT NOT NULL" },
        { "name": "URLRegionID", "type": "INTEGER NOT NULL" },
        { "name": "ResolutionWidth", "type": "SMALLINT NOT NULL" },
        { "name": "ResolutionHeight", "type": "SMALLINT NOT NULL" },
        { "name": "ResolutionDepth", "type": "SMALLINT NOT NULL" },
        { "name": "FlashMajor", "type": "SMALLINT NOT NULL" },
        { "name": "FlashMinor", "type": "SMALLINT NOT NULL" },
        { "name": "FlashMinor2", "type": "TEXT NOT NULL" },
        { "name": "NetMajor", "type": "SMALLINT NOT NULL" },
        { "name": "NetMinor", "type": "SMALLINT NOT NULL" },
        { "name": "UserAgentMajor", "type": "SMALLINT NOT NULL" },
        { "name": "UserAgentMinor", "type": "VARCHAR(255) NOT NULL" },
        { "name": "CookieEnable", "type": "SMALLINT NOT NULL" },
        { "name": "JavascriptEnable", "type": "SMALLINT NOT NULL" },
        { "name": "IsMobile", "type": "SMALLINT NOT NULL" },
        { "name": "MobilePhone", "type": "SMALLINT NOT NULL" },
        { "name": "MobilePhoneModel", "type": "TEXT NOT NULL" },
        { "name": "Params", "type": "TEXT NOT NULL" },
        { "name": "IPNetworkID", "type": "INTEGER NOT NULL" },
        { "name": "TraficSourceID", "type": "SMALLINT NOT NULL" },
        { "name": "SearchEngineID", "type": "SMALLINT NOT NULL" },
        { "name": "SearchPhrase", "type": "TEXT NOT NULL" },
        { "name": "AdvEngineID", "type": "SMALLINT NOT NULL" },
        { "name": "IsArtifical", "type": "SMALLINT NOT NULL" },
        { "name": "WindowClientWidth", "type": "SMALLINT NOT NULL" },
        { "name": "WindowClientHeight", "type": "SMALLINT NOT NULL" },
        { "name": "ClientTimeZone", "type": "SMALLINT NOT NULL" },
        { "name": "ClientEventTime", "type": "TIMESTAMP NOT NULL" },
        { "name": "SilverlightVersion1", "type": "SMALLINT NOT NULL" },
        { "name": "SilverlightVersion2", "type": "SMALLINT NOT NULL" },
        { "name": "SilverlightVersion3", "type": "INTEGER NOT NULL" },
        { "name": "SilverlightVersion4", "type": "SMALLINT NOT NULL" },
        { "name": "PageCharset", "type": "TEXT NOT NULL" },
        { "name": "CodeVersion", "type": "INTEGER NOT NULL" },
        { "name": "IsLink", "type": "SMALLINT NOT NULL" },
        { "name": "IsDownload", "type": "SMALLINT NOT NULL" },
        { "name": "IsNotBounce", "type": "SMALLINT NOT NULL" },
        { "name": "FUniqID", "type": "BIGINT NOT NULL" },
        { "name": "OriginalURL", "type": "TEXT NOT NULL" },
        { "name": "HID", "type": "INTEGER NOT NULL" },
        { "name": "IsOldCounter", "type": "SMALLINT NOT NULL" },
        { "name": "IsEvent", "type": "SMALLINT NOT NULL" },
        { "name": "IsParameter", "type": "SMALLINT NOT NULL" },
        { "name": "DontCountHits", "type": "SMALLINT NOT NULL" },
        { "name": "WithHash", "type": "SMALLINT NOT NULL" },
        { "name": "HitColor", "type": "CHAR NOT NULL" },
        { "name": "LocalEventTime", "type": "TIMESTAMP NOT NULL" },
        { "name": "Age", "type": "SMALLINT NOT NULL" },
        { "name": "Sex", "type": "SMALLINT NOT NULL" },
        { "name": "Income", "type": "SMALLINT NOT NULL" },
        { "name": "Interests", "type": "SMALLINT NOT NULL" },
        { "name": "Robotness", "type": "SMALLINT NOT NULL" },
        { "name": "RemoteIP", "type": "INTEGER NOT NULL" },
        { "name": "WindowName", "type": "INTEGER NOT NULL" },
        { "name": "OpenerName", "type": "INTEGER NOT NULL" },
        { "name": "HistoryLength", "type": "SMALLINT NOT NULL" },
        { "name": "BrowserLanguage", "type": "TEXT NOT NULL" },
        { "name": "BrowserCountry", "type": "TEXT NOT NULL" },
        { "name": "SocialNetwork", "type": "TEXT NOT NULL" },
        { "name": "SocialAction", "type": "TEXT NOT NULL" },
        { "name": "HTTPError", "type": "SMALLINT NOT NULL" },
        { "name": "SendTiming", "type": "INTEGER NOT NULL" },
        { "name": "DNSTiming", "type": "INTEGER NOT NULL" },
        { "name": "ConnectTiming", "type": "INTEGER NOT NULL" },
        { "name": "ResponseStartTiming", "type": "INTEGER NOT NULL" },
        { "name": "ResponseEndTiming", "type": "INTEGER NOT NULL" },
        { "name": "FetchTiming", "type": "INTEGER NOT NULL" },
        { "name": "SocialSourceNetworkID", "type": "SMALLINT NOT NULL" },
        { "name": "SocialSourcePage", "type": "TEXT NOT NULL" },
        { "name": "ParamPrice", "type": "BIGINT NOT NULL" },
        { "name": "ParamOrderID", "type": "TEXT NOT NULL" },
        { "name": "ParamCurrency", "type": "TEXT NOT NULL" },
        { "name": "ParamCurrencyID", "type": "SMALLINT NOT NULL" },
        { "name": "OpenstatServiceName", "type": "TEXT NOT NULL" },
        { "name": "OpenstatCampaignID", "type": "TEXT NOT NULL" },
        { "name": "OpenstatAdID", "type": "TEXT NOT NULL" },
        { "name": "OpenstatSourceID", "type": "TEXT NOT NULL" },
        { "name": "UTMSource", "type": "TEXT NOT NULL" },
        { "name": "UTMMedium", "type": "TEXT NOT NULL" },
        { "name": "UTMCampaign", "type": "TEXT NOT NULL" },
        { "name": "UTMContent", "type": "TEXT NOT NULL" },
        { "name": "UTMTerm", "type": "TEXT NOT NULL" },
        { "name": "FromTag", "type": "TEXT NOT NULL" },
        { "name": "HasGCLID", "type": "SMALLINT NOT NULL" },
        { "name": "RefererHash", "type": "BIGINT NOT NULL" },
        { "name": "URLHash", "type": "BIGINT NOT NULL" },
        { "name": "CLID", "type": "INTEGER NOT NULL" }
      ],
      "primary key": { "columns": [ "CounterID", "EventDate", "UserID", "EventTime", "WatchID" ] }
    }
  ]
}

=== SQL-Storm/OLAPBench/benchmarks/stackoverflow/stackoverflow.dbschema.json
{
  "file_ending": "csv",
  "delimiter": ",",
  "format": "csv",
  "null": "",
  "escape_names": false,
  "tables": [
    {
      "name": "PostHistoryTypes",
      "columns": [
        { "name": "Id", "type": "smallint not null" },
        { "name": "Name", "type": "varchar(50) not null" }
      ],
      "primary key": { "column": "Id" }
    },
    {
      "name": "LinkTypes",
      "columns": [
        { "name": "Id", "type": "smallint not null" },
        { "name": "Name", "type": "varchar(50) not null" }
      ],
      "primary key": { "column": "Id" }
    },
    {
      "name": "PostTypes",
      "columns": [
        { "name": "Id", "type": "smallint not null" },
        { "name": "Name", "type": "varchar(50) not null" }
      ],
      "primary key": { "column": "Id" }
    },
    {
      "name": "CloseReasonTypes",
      "columns": [
        { "name": "Id", "type": "smallint not null" },
        { "name": "Name", "type": "varchar(50) not null" }
      ],
      "primary key": { "column": "Id" }
    },
    {
      "name": "VoteTypes",
      "columns": [
        { "name": "Id", "type": "smallint not null" },
        { "name": "Name", "type": "varchar(50) not null" }
      ],
      "primary key": { "column": "Id" }
    },
    {
      "name": "Users",
      "columns": [
        { "name": "Id", "type": "int not null" },
        { "name": "Reputation", "type": "int not null" },
        { "name": "CreationDate", "type": "timestamp not null" },
        { "name": "DisplayName", "type": "varchar(100)" },
        { "name": "LastAccessDate", "type": "timestamp not null" },
        { "name": "WebsiteUrl", "type": "varchar(200)" },
        { "name": "Location", "type": "varchar(300)" },
        { "name": "AboutMe", "type": "text" },
        { "name": "Views", "type": "int" },
        { "name": "UpVotes", "type": "int" },
        { "name": "DownVotes", "type": "int" },
        { "name": "ProfileImageUrl", "type": "varchar(200)" },
        { "name": "AccountId", "type": "bigint" }
      ],
      "primary key": { "column": "Id" }
    },
    {
      "name": "Badges",
      "columns": [
        { "name": "Id", "type": "int not null" },
        { "name": "UserId", "type": "int not null" },
        { "name": "Name", "type": "varchar(50) not null" },
        { "name": "Date", "type": "timestamp not null" },
        { "name": "Class", "type": "smallint not null" },
        { "name": "TagBased", "type": "bool not null" }
      ],
      "primary key": { "column": "Id" },
      "foreign keys": [ { "column": "UserId", "foreign table": "Users", "foreign column": "Id" } ]
    },
    {
      "name": "Posts",
      "columns": [
        { "name": "Id", "type": "int not null" },
        { "name": "PostTypeId", "type": "smallint" },
        { "name": "AcceptedAnswerId", "type": "int" },
        { "name": "ParentId", "type": "int" },
        { "name": "CreationDate", "type": "timestamp" },
        { "name": "Score", "type": "int" },
        { "name": "ViewCount", "type": "int" },
        { "name": "Body", "type": "text" },
        { "name": "OwnerUserId", "type": "int" },
        { "name": "OwnerDisplayName", "type": "varchar(100)" },
        { "name": "LastEditorUserId", "type": "int" },
        { "name": "LastEditorDisplayName", "type": "varchar(100)" },
        { "name": "LastEditDate", "type": "timestamp" },
        { "name": "LastActivityDate", "type": "timestamp" },
        { "name": "Title", "type": "varchar(300)" },
        { "name": "Tags", "type": "varchar(4000)" },
        { "name": "AnswerCount", "type": "int" },
        { "name": "CommentCount", "type": "int" },
        { "name": "FavoriteCount", "type": "int" },
        { "name": "ClosedDate", "type": "timestamp" },
        { "name": "CommunityOwnedDate", "type": "timestamp" },
        { "name": "ContentLicense", "type": "varchar(30)" }
      ],
      "primary key": { "column": "Id" },
      "foreign keys": [
        { "column": "PostTypeId", "foreign table": "PostTypes", "foreign column": "Id" },
        { "column": "AcceptedAnswerId", "foreign table": "Posts", "foreign column": "Id" },
        { "column": "ParentId", "foreign table": "Posts", "foreign column": "Id" },
        { "column": "OwnerUserId", "foreign table": "Users", "foreign column": "Id" },
        { "column": "LastEditorUserId", "foreign table": "Users", "foreign column": "Id" }
      ]
    },
    {
      "name": "Comments",
      "columns": [
        { "name": "Id", "type": "int not null" },
        { "name": "PostId", "type": "int not null" },
        { "name": "Score", "type": "int" },
        { "name": "Text", "type": "varchar(2000) not null" },
        { "name": "CreationDate", "type": "timestamp not null" },
        { "name": "UserDisplayName", "type": "varchar(100)" },
        { "name": "UserId", "type": "int" },
        { "name": "ContentLicense", "type": "varchar(30)" }
      ],
      "primary key": { "column": "Id" },
      "foreign keys": [
        { "column": "PostId", "foreign table": "Posts", "foreign column": "Id" },
        { "column": "UserId", "foreign table": "Users", "foreign column": "Id" }
      ]
    },
    {
      "name": "PostHistory",
      "columns": [
        { "name": "Id", "type": "int not null" },
        { "name": "PostHistoryTypeId", "type": "smallint" },
        { "name": "PostId", "type": "int" },
        { "name": "RevisionGUID", "type": "varchar(36)" },
        { "name": "CreationDate", "type": "timestamp" },
        { "name": "UserId", "type": "int" },
        { "name": "UserDisplayName", "type": "varchar(100)" },
        { "name": "Comment", "type": "varchar(800)" },
        { "name": "Text", "type": "text" },
        { "name": "ContentLicense", "type": "varchar(30)" }
      ],
      "primary key": { "column": "Id" },
      "foreign keys": [
        { "column": "PostHistoryTypeId", "foreign table": "PostHistoryTypes", "foreign column": "Id" },
        { "column": "PostId", "foreign table": "Posts", "foreign column": "Id" },
        { "column": "UserId", "foreign table": "Users", "foreign column": "Id" }
      ]
    },
    {
      "name": "PostLinks",
      "columns": [
        { "name": "Id", "type": "bigint not null" },
        { "name": "CreationDate", "type": "timestamp not null" },
        { "name": "PostId", "type": "int not null" },
        { "name": "RelatedPostId", "type": "int not null" },
        { "name": "LinkTypeId", "type": "smallint not null" }
      ],
      "primary key": { "column": "Id" },
      "foreign keys": [
        { "column": "PostId", "foreign table": "Posts", "foreign column": "Id" },
        { "column": "RelatedPostId", "foreign table": "Posts", "foreign column": "Id" },
        { "column": "LinkTypeId", "foreign table": "LinkTypes", "foreign column": "Id" }
      ]
    },
    {
      "name": "Tags",
      "columns": [
        { "name": "Id", "type": "int not null" },
        { "name": "TagName", "type": "varchar(35)" },
        { "name": "Count", "type": "int not null" },
        { "name": "ExcerptPostId", "type": "int" },
        { "name": "WikiPostId", "type": "int" },
        { "name": "IsModeratorOnly", "type": "bool" },
        { "name": "IsRequired", "type": "bool" }
      ],
      "primary key": { "column": "Id" },
      "foreign keys": [
        { "column": "ExcerptPostId", "foreign table": "Posts", "foreign column": "Id" },
        { "column": "WikiPostId", "foreign table": "Posts", "foreign column": "Id" }
      ]
    },
    {
      "name": "Votes",
      "columns": [
        { "name": "Id", "type": "int not null" },
        { "name": "PostId", "type": "int not null" },
        { "name": "VoteTypeId", "type": "smallint not null" },
        { "name": "UserId", "type": "int" },
        { "name": "CreationDate", "type": "timestamp" },
        { "name": "BountyAmount", "type": "int" }
      ],
      "primary key": { "column": "Id" },
      "foreign keys": [
        { "column": "VoteTypeId", "foreign table": "VoteTypes", "foreign column": "Id" },
        { "column": "UserId", "foreign table": "Users", "foreign column": "Id" }
      ]
    }
  ]
}
